In [8]:
x = 'Rin'
y = 'dha'
x + ' & ' + y

'Rin & dha'

In [9]:
x = 'Rindha'
x * 2

'RindhaRindha'

In [10]:
z1 = x[2:] 

print(z1)

ndha


In [11]:
z2 = y[0] + y[1] 

print(z2)

dh


In [5]:
x = '4'
y = '2'

x + y


'42'

In [12]:
str.capitalize('rindha')

'Rindha'

In [13]:
str1 = "Cake 4 U"
str2 = "404"
len(str1)

8

In [14]:
str1.isdigit()

False

In [15]:
str2.isdigit()


True

In [16]:
str1.replace('4 U', str2)

'Cake 404'

In [17]:
str1 = 'Rindha'
str2 = 'rin'
str1.find(str2)

-1

In [20]:
str1 = 'I got you a milk'
str2 = 'milk'
str1.find(str2)

12

In [21]:
x = 4
y = 2
x == y

False

In [22]:
x > y

True

In [23]:
x = 4
y = 2
z = (x==y) 
if z: # 
    print("Rindha")
else: print("No Rindha")

No Rindha


In [25]:
i = 8.0
type(i)

float

In [27]:
x = 4

y = 2 

z = x/y

type(z)

int

In [28]:
x = 2
y = "The Godfather: Part "
fav_movie = (y) + str(x)
print(fav_movie)

The Godfather: Part 2


In [29]:
import array as arr
a = arr.array("I",[3,6,9])
type(a)


array.array

In [30]:
x = []
type(x)

list

In [31]:
x1 = [1,2,3]
type(x1)

list

In [32]:
x2 = list([1,'apple',3])
type(x2)

list

In [33]:
print(x2[1])

apple


In [34]:
x2[1] = 'orange'
print(x2)

[1, 'orange', 3]


In [35]:
list_num = [1,2,45,6,7,2,90,23,435]
list_char = ['r','i','n','d','h','a']

list_num.append(11)
print(list_num)

[1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [36]:
list_num.insert(0, 11)
print(list_num)

[11, 1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [37]:
list_char.remove('i') 
print(list_char)

['r', 'n', 'd', 'h', 'a']


In [38]:
list_char.pop(-2)
print(list_char)

['r', 'n', 'd', 'a']


In [39]:
list_num.sort()
print(list_num)

[1, 2, 2, 6, 7, 11, 11, 23, 45, 90, 435]


In [40]:
list.reverse(list_num)
print(list_num)

[435, 90, 45, 23, 11, 11, 7, 6, 2, 2, 1]


In [41]:
array_char = array.array("u",["c","a","t","s"])
array_char.tostring()
print(array_char)

NameError: name 'array' is not defined

In [42]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3
print(arr_b)

[1 2 3]


In [43]:
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [44]:
multi_arr_ones = np.ones((3,4)) 
print(multi_arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
stack = [1,2,3,4,5] 
stack.append(6)
print(stack)

[1, 2, 3, 4, 5, 6]


In [46]:
stack.pop()
stack.pop()
print(stack)

[1, 2, 3, 4]


In [47]:
graph = { "a" : ["c", "d"],
          "b" : ["d", "e"],
          "c" : ["a", "e"],
          "d" : ["a", "b"],
          "e" : ["b", "c"]
        }

def define_edges(graph):
    edges = []
    for vertices in graph:
        for neighbour in graph[vertices]:
            edges.append((vertices, neighbour))
    return edges

print(define_edges(graph))

[('a', 'c'), ('a', 'd'), ('c', 'a'), ('c', 'e'), ('b', 'd'), ('b', 'e'), ('e', 'b'), ('e', 'c'), ('d', 'a'), ('d', 'b')]


In [49]:
class Tree:
    def __init__(self, info, left=None, right=None):
        self.info = info
        self.left  = left
        self.right = right

    def __str__(self):
        return (str(self.info) + ', Left child: ' + str(self.left) + ', Right child: ' + str(self.right))

tree = Tree(1, Tree(2, 2.1, 2.2), Tree(3, 3.1))
print(tree)

1, Left child: 2, Left child: 2.1, Right child: 2.2, Right child: 3, Left child: 3.1, Right child: None
